[package]
name = "translator-popup-tauri"
version = "0.1.0"
edition = "2024"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-global-shortcut = "2"
tauri-plugin-single-instance = "2"
tokio = { version = "1.53.1", features = ["macros", "net", "rt", "time"] }
translator-core = { version = "0.1.0", path = "../translator-core" }
translator-service = { version = "0.1.0", path = "../../core/translator-service" }

[target.'cfg(any(target_os = "windows", target_os = "macos"))'.dependencies]
arboard = "3.6.1"
enigo = "0.6.1"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_System_DataExchange",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }
